version: "3.8"
services:
  tubastore_app:
    container_name: tubastore_app
    image: node:18-alpine3.15
    working_dir: /app
    command: sh -c "export TZ='Asia/Ho_Chi_Minh' && yarn && yarn sequelize:run && yarn start:dev"
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - tuba-network
    volumes:
      - ./:/app
      - .env:/app/.env
      - ./public:/app/public
    depends_on:
      - tubastore_postgres
  tubastore_postgres:
    image: postgres:15.3
    container_name: tubastore_postgres
    restart: always
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      PGTZ: 'Asia/Ho_Chi_Minh'
      POSTGRES_PASSWORD: postgres
    ports:
      - "54320:5432"
    volumes:
      - './storages/postgres/data:/var/lib/postgresql/data'
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
    networks:
      - tuba-network
networks:
  tuba-network:
    driver: 'bridge'
